# Generated by Django 4.1.4 on 2023-02-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=674128573, max_length=15, unique=True, verbose_name='phone_number'),
            preserve_default=False,
        ),
    ]
