# Generated by Django 4.1.4 on 2023-02-01 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quater', models.CharField(blank=True, max_length=256, null=True)),
                ('house_type', models.CharField(max_length=256, null=True)),
                ('room_nb', models.IntegerField(default=0)),
                ('toilet_nb', models.IntegerField(default=0)),
                ('kitchen_nb', models.IntegerField(default=0)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='house')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='house')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='house')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='house')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='house')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='house')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
