# Generated by Django 4.1.4 on 2023-02-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
